export enum CollectionNames {
    SLOTS = 'slots',
    EGG_COUNT = 'egg_count',
    EGGS = 'eggs',
    PLANS = 'Plans',
    ACTIVE_PLAN = 'active_plan',
    PAST_PLANS = 'past_plans',
    ARCHIVED_PLANS = 'archived_plans',
    SNAPSHOTS = 'Snapshots',
    DAILY_READINGS = 'daily_readings',
    HOURLY_READINGS = 'hourly_readings',
    DAILY_AVERAGE = 'daily_average',
    ALL_READINGS = 'Readings',
    FAQS = 'FAQs',
    DEVICE_PLAN_SUMMARY = 'device_plans',
    PINGPONG = 'PingPong',
    ADMIN_USERS = 'admin_users',
    APP_USERS = 'users',
    NOTIFICATIONS = 'Notifications',
    REPORTS = "Reports",
    COMMENTS = "Comments",
    POSTS = "Posts",
    AVATARS = "Avatars",
    CLOTHES = "Clothes",
    CLOTHES_SMPL ="SMPL_Clothes",
    USERS = "users",
    DATA_PRIVACY_CONSENT = "DataPrivacyConsent"
}